<?php

declare(strict_types=1);

namespace Atelier\Diagram\Tests\Git;

use Atelier\Diagram\Exception\InvalidDiagramException;
use Atelier\Diagram\Git\Branch;
use Atelier\Diagram\Git\Commit;
use Atelier\Diagram\Git\GitGraph;
use Atelier\Diagram\Git\GitGraphBuilder;
use Atelier\Diagram\Model\Direction;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(GitGraphBuilder::class)]
#[CoversClass(GitGraph::class)]
#[CoversClass(Branch::class)]
#[CoversClass(Commit::class)]
final class GitGraphBuilderTest extends TestCase
{
    public function testBuildsBranchesCommitsAndMergeWithTwoParents(): void
    {
        $graph = (new GitGraphBuilder())
            ->title('Release flow')
            ->commit('c1')
            ->branch('feature')
            ->commit(id: 'c2', tag: 'v0.1')
            ->checkout('main')
            ->merge('feature')
            ->build();

        $this->assertSame('Release flow', $graph->title?->text);
        $this->assertSame(Direction::LeftToRight, $graph->direction);
        $this->assertTrue($graph->showLegend);

        $this->assertSame(['main', 'feature'], array_map(static fn (Branch $b): string => $b->name, $graph->branches));
        $this->assertNull($graph->branches[0]->createdAt);
        $this->assertSame('c1', $graph->branches[1]->createdAt);

        $this->assertCount(3, $graph->commits);

        $first = $graph->commits[0];
        $this->assertSame('c1', $first->id);
        $this->assertSame('main', $first->branch);
        $this->assertSame([], $first->parents);
        $this->assertFalse($first->isMerge());

        $featureCommit = $graph->commits[1];
        $this->assertSame('c2', $featureCommit->id);
        $this->assertSame('feature', $featureCommit->branch);
        $this->assertSame('v0.1', $featureCommit->tag);
        $this->assertSame(['c1'], $featureCommit->parents);

        $mergeCommit = $graph->commits[2];
        $this->assertSame('main', $mergeCommit->branch);
        $this->assertTrue($mergeCommit->isMerge());
        $this->assertSame(['c1', 'c2'], $mergeCommit->parents);
    }

    public function testAutoGeneratedCommitIdsAreDeterministic(): void
    {
        $build = static fn (): GitGraph => (new GitGraphBuilder())
            ->commit()
            ->commit()
            ->build();

        $first = array_map(static fn (Commit $c): string => $c->id, $build()->commits);
        $second = array_map(static fn (Commit $c): string => $c->id, $build()->commits);

        $this->assertSame($first, $second);
        $this->assertNotSame($first[0], $first[1]);
        $this->assertMatchesRegularExpression('/^[0-9a-f]{7}$/', $first[0]);
    }

    public function testWithoutLegendDisablesLegend(): void
    {
        $graph = (new GitGraphBuilder())
            ->withoutLegend()
            ->commit()
            ->build();

        $this->assertFalse($graph->showLegend);
    }

    public function testRejectsDuplicateExplicitCommitId(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('Commit id "c1" is already used');

        (new GitGraphBuilder())
            ->commit('c1')
            ->commit('c1');
    }

    public function testRejectsDuplicateBranch(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('Branch "feature" already exists');

        (new GitGraphBuilder())
            ->branch('feature')
            ->branch('feature');
    }

    public function testRejectsCheckoutOfUnknownBranch(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('Cannot checkout unknown branch "ghost"');

        (new GitGraphBuilder())->checkout('ghost');
    }

    public function testRejectsMergeOfUnknownBranch(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('Cannot merge unknown branch "ghost"');

        (new GitGraphBuilder())
            ->commit()
            ->merge('ghost');
    }

    public function testRejectsMergeOfBranchIntoItself(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('into itself');

        (new GitGraphBuilder())
            ->commit()
            ->merge('main');
    }

    public function testRejectsMergeOfBranchWithoutCommits(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('it has no commits');

        (new GitGraphBuilder())
            ->branch('feature')
            ->checkout('main')
            ->commit()
            ->merge('feature');
    }

    public function testRejectsMergeIntoBranchWithoutCommits(): void
    {
        $this->expectException(InvalidDiagramException::class);
        $this->expectExceptionMessage('Cannot merge into branch "main": it has no commits.');

        (new GitGraphBuilder())
            ->branch('feature')
            ->commit()
            ->checkout('main')
            ->merge('feature');
    }
}
