<?php

declare(strict_types=1);

namespace Atelier\Diagram\Git;

/**
 * One commit in a git graph.
 *
 * Carries no geometry: position comes from the operation order in
 * GitGraph::$commits, color from the branch lane.
 */
final readonly class Commit
{
    /**
     * @param string       $id      short commit id, auto-generated by the builder when omitted
     * @param string       $branch  name of the branch the commit was made on
     * @param string|null  $tag     tag attached to the commit, null for none
     * @param list<string> $parents parent commit ids -- empty for a root commit,
     *                              one for a regular commit, two for a merge commit
     */
    public function __construct(
        public string $id,
        public string $branch,
        public ?string $tag = null,
        public array $parents = [],
    ) {
    }

    /**
     * Whether this commit is a merge commit (two parents).
     */
    public function isMerge(): bool
    {
        return \count($this->parents) >= 2;
    }
}
