<?php

declare(strict_types=1);

namespace Atelier\Diagram\Tests\Mindmap;

use Atelier\Diagram\Exception\InvalidArgumentException;
use Atelier\Diagram\Mindmap\MindmapDiagram;
use Atelier\Diagram\Mindmap\MindmapDiagramBuilder;
use Atelier\Diagram\Mindmap\MindmapNode;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(MindmapDiagramBuilder::class)]
#[CoversClass(MindmapDiagram::class)]
#[CoversClass(MindmapNode::class)]
final class MindmapDiagramBuilderTest extends TestCase
{
    public function testBuildsRootedTree(): void
    {
        $diagram = (new MindmapDiagramBuilder())
            ->root('Atelier', 'root')
            ->child('root', 'Layout', 'layout')
            ->child('layout', 'Grid', 'grid')
            ->child('root', 'Diagram', 'diagram')
            ->build();

        $this->assertSame('Atelier', $diagram->root->label);
        $this->assertSame(['Layout', 'Grid', 'Diagram'], array_map(static fn (MindmapNode $node): string => $node->label, array_slice($diagram->nodesDepthFirst(), 1)));
        $this->assertSame('Grid', $diagram->root->children[0]->children[0]->label);
    }

    public function testBuildsWithAutoGeneratedIds(): void
    {
        $diagram = (new MindmapDiagramBuilder())
            ->root('Root')
            ->child('mindmap_node_1', 'Child')
            ->build();

        $this->assertSame('mindmap_node_1', $diagram->root->id);
        $this->assertSame('mindmap_node_2', $diagram->root->children[0]->id);
    }

    public function testRejectsDuplicateRoot(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('exactly one root');

        (new MindmapDiagramBuilder())
            ->root('One', 'one')
            ->root('Two', 'two');
    }

    public function testRejectsUnknownParent(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('unknown parent');

        (new MindmapDiagramBuilder())->child('missing', 'Node');
    }

    public function testRejectsEmptyDiagram(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('exactly one root');

        (new MindmapDiagramBuilder())->build();
    }

    public function testRejectsEmptyNodeId(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('node id must be non-empty');

        (new MindmapDiagramBuilder())->root('Label', '   ');
    }

    public function testRejectsEmptyNodeLabel(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('node label must be non-empty');

        (new MindmapDiagramBuilder())->root('   ', 'id');
    }

    public function testRejectsDuplicateNodeId(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Duplicate mindmap node id "x"');

        (new MindmapDiagramBuilder())
            ->root('Root', 'x')
            ->child('x', 'Child', 'x');
    }

    public function testNodeConstructsWithChildren(): void
    {
        $node = new MindmapNode('id', 'Label', [new MindmapNode('child', 'Child')]);

        $this->assertSame('id', $node->id);
        $this->assertSame('Label', $node->label);
        $this->assertSame('Child', $node->children[0]->label);
    }

    public function testNodeRejectsEmptyId(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('node id must be non-empty');

        new MindmapNode('   ', 'Label');
    }

    public function testNodeRejectsEmptyLabel(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('node label must be non-empty');

        new MindmapNode('id', '   ');
    }
}
